export const defaultDoctors = [
  {
    _id: 'doc1',
    name: 'Dr. Richard James',
    email: 'richard.james@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc1.png',
    speciality: 'General physician',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Richard James has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '17th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc2',
    name: 'Dr. Emily Larson',
    email: 'emily.larson@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc2.png',
    speciality: 'Gynecologist',
    degree: 'MBBS',
    experience: '3 Years',
    about: 'Dr. Emily Larson has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 60,
    available: true,
    address: { line1: '27th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc3',
    name: 'Dr. Sarah Patel',
    email: 'sarah.patel@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc3.png',
    speciality: 'Dermatologist',
    degree: 'MBBS',
    experience: '1 Years',
    about: 'Dr. Sarah Patel has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 30,
    available: true,
    address: { line1: '37th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc4',
    name: 'Dr. Christopher Lee',
    email: 'christopher.lee@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc4.png',
    speciality: 'Pediatricians',
    degree: 'MBBS',
    experience: '2 Years',
    about: 'Dr. Christopher Lee has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 40,
    available: true,
    address: { line1: '47th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc5',
    name: 'Dr. Jennifer Garcia',
    email: 'jennifer.garcia@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc5.png',
    speciality: 'Neurologist',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Jennifer Garcia has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '57th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc6',
    name: 'Dr. Andrew Williams',
    email: 'andrew.williams@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc6.png',
    speciality: 'Neurologist',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Andrew Williams has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '57th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc7',
    name: 'Dr. Christopher Davis',
    email: 'christopher.davis@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc7.png',
    speciality: 'General physician',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Christopher Davis has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '17th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc8',
    name: 'Dr. Timothy White',
    email: 'timothy.white@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc8.png',
    speciality: 'Gynecologist',
    degree: 'MBBS',
    experience: '3 Years',
    about: 'Dr. Timothy White has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 60,
    available: true,
    address: { line1: '27th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc9',
    name: 'Dr. Ava Mitchell',
    email: 'ava.mitchell@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc9.png',
    speciality: 'Dermatologist',
    degree: 'MBBS',
    experience: '1 Years',
    about: 'Dr. Ava Mitchell has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 30,
    available: true,
    address: { line1: '37th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc10',
    name: 'Dr. Jeffrey King',
    email: 'jeffrey.king@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc10.png',
    speciality: 'Pediatricians',
    degree: 'MBBS',
    experience: '2 Years',
    about: 'Dr. Jeffrey King has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 40,
    available: true,
    address: { line1: '47th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc11',
    name: 'Dr. Zoe Kelly',
    email: 'zoe.kelly@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc11.png',
    speciality: 'Neurologist',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Zoe Kelly has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '57th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  },
  {
    _id: 'doc12',
    name: 'Dr. Patrick Harris',
    email: 'patrick.harris@example.com',
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/prescripto/doc12.png',
    speciality: 'Gastroenterologist',
    degree: 'MBBS',
    experience: '4 Years',
    about: 'Dr. Patrick Harris has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective management strategies.',
    fees: 50,
    available: true,
    address: { line1: '57th Cross, Richmond', line2: 'Circle, Ring Road, London' },
    slots_booked: {}
  }
];
